### ISSUE TITLE
Add Travis-CI support

### ISSUE THREAD

**Issue by kaneplusplus** [kaneplusplus/bigmemory#10]

**Comment by kaneplusplus** [comment]
Added and building successfully.

**Comment by cdeterman** [comment]
Is the multiple OS option working?  I thought it was currently in development and not yet available.  Did you find someplace that said otherwise?  I am just a little skeptical to make sure it isn't just building on the first os listed (i.e. linux).

**Comment by kaneplusplus** [comment]
It looks like it's still only installing on Linux. I resorted to building on my Mac (and suppressing deprecated-declarations from BH). 

The Appveyor builds don't look right. They should be creating artifacts from the 00install.log and 00config.log but they are not. I'm trying the winbuilder now.

**Comment by cdeterman** [comment]
It does look like the if we contact them at support@travis-ci.com and say which repo to enable then the option should be available.  This was noted on the [Travis-CI Blog](http://docs.travis-ci.com/user/multi-os/).

**Comment by kaneplusplus** [comment]
OK, I'll take a look.
