### ISSUE TITLE
description(): user-defined file name

### ISSUE THREAD

**Issue by nperezzanon** [kaneplusplus/bigmemory#101]
Hi,

I would like to specify the file name for the shared object, and I have tried the following lines:

```
data_array <- bigmemory::big.matrix(nrow = prod(final_dims), ncol = 1)
    shared_matrix_pointer <- bigmemory::describe(data_array)
    if (!is.null(ObjectBigmemory)) {
      attr(shared_matrix_pointer, 'description')$sharedName <- ObjectBigmemory
    }
```

Although I can see that the attribute has correctly changed, the file has the original name. I guess that the file is already created by `describe()`, so, when I change the name is too late.

Do you know if there is a way to change this name?

Thanks in advance,

Núria

**Comment by kaneplusplus** [comment]
Please see the `backingfile` and `descriptorfile` options to the `big.matrix()` function.
