### ISSUE TITLE
Windows - How to free memory used by big.matrix objects of crashed R sessions

### ISSUE THREAD

**Issue by RdeBiotec** [kaneplusplus/bigmemory#102]
Hi!

So I was fortunate enough to have some RStudio crashes while testing bigmemory code in Windows.  I wasn't using filepaths in some cases, so I don't know where the temporary big.matrixes were stored. 

In Linux it would be in /dev/shm, but... where should I search in Windows? Using the File Explorer to find these was not very helpful.

Hopefully someone can lend me a hand. Thanks!

**Comment by kaneplusplus** [comment]
If you type:

```{r}
tempdir()
```

It should give you the directory. Note that I think a new temp directory is defined per R session so you may need to look in the parent directory.

**Comment by RdeBiotec** [comment]
Thanks a lot!!! Worked like a charm 🥇
