### ISSUE TITLE
"Put this matrix on disk"

### ISSUE THREAD

**Issue by multimeric** [kaneplusplus/bigmemory#116]
I'm trying to find the right function that will take an existing matrix `m` and convert it to a disk-backed one. 

I've tried this, but it seems to fill the matrix with `m[[1]]` instead of copying all the data.
```R
bigmemory::filebacked.big.matrix(
  nrow = nrow(m),
  ncol = ncol(m),
  init = m,
  ...
)
```

I've also tried this, and while it does return a `big.memory` object, it's not filebacked:

```R
proxy <- bigmemory::as.big.matrix(m)
bigmemory::is.filebacked(proxy)
# [1] FALSE
```

The only working solution I can find is a bit ugly:
```R
proxy <- bigmemory::filebacked.big.matrix(nrow = nrow(m), ncol=ncol(m), ...)
proxy[] <- m
bigmemory::is.filebacked(proxy)
# [1] TRUE
```

**Comment by privefl** [comment]
You probably need to specify `backingfile` and `backingpath` in `as.big.matrix()`.

**Comment by multimeric** [comment]
Good point. I thought I had tried this but apparently not!

```R
proxy <- bigmemory::as.big.matrix(m, backingpath = tempdir(), backingfile = "m.bin", descriptorfile = "m.desc")
bigmemory::is.filebacked(proxy)
# [1] TRUE
```
