### ISSUE TITLE
Add Coveralls Testing

### ISSUE THREAD

**Issue by kaneplusplus** [kaneplusplus/bigmemory#12]

**Comment by cdeterman** [comment]
This has now been added.

**Comment by phaverty** [comment]
Great!  Bioconductor added something similar recently. It is quite helpful.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

On Thu, Jul 23, 2015 at 10:08 AM, Charles Determan <notifications@github.com

**Comment by cdeterman** [comment]
Indeed, it is great to see how much of the code has been tested.  It integrates nicely with the testthat package.  Strangely this issue doesn't have the option to close now???

**Comment by cdeterman** [comment]
@kaneplusplus hmm... it appears that your specific coveralls isn't working at the moment.  The coveralls I use on [my fork](https://coveralls.io/github/cdeterman/bigmemory) shows the coverage at ~55%.  Perhaps a switch hasn't been hit on your end?

**Comment by kaneplusplus** [comment]
It looks like coveralls.io is doing some updating and is read only right now. I'll give it a day or two before looking for a problem. 

BTW 55% is great.

**Comment by kaneplusplus** [comment]
OK, it looks like the coveralls upgrade is complete and I'm seeing 55% coverage in the badge. In the next  couple of days I'll take another looks and see what, if anything needs to be done for the next submission of bigmemory to CRAN.
