### ISSUE TITLE
Windows won't create consecutive filebacked.big.matrix objects

### ISSUE THREAD

**Issue by cdeterman** [kaneplusplus/bigmemory#15]
For some strange reason, Windows builds but errors out when you try to build a `filebacked.big.matrix` object a second time.  This results in problems when trying to run the testing framework.  The following reproduces the problem:

```r
z <- filebacked.big.matrix(3, 3, type='integer', init=123,
                           backingfile="example.bin",
                           descriptorfile="example.desc",
                           dimnames=list(c('a','b','c'), c('d', 'e', 'f')))

z <- filebacked.big.matrix(3, 3, type='integer', init=123,
                           backingfile="example.bin",
                           descriptorfile="example.desc",
                           dimnames=list(c('a','b','c'), c('d', 'e', 'f')))

Error in CreateFileBackedBigMatrix(as.character(backingfile), as.character(backingpath),  : 
  Problem creating filebacked matrix.
```
So this is clearly having issues with the `create` function on line 2558 of bigmemory.cpp.  I have no idea at the moment why this is happening as it is not reproducible on linux.

**Comment by kaneplusplus** [comment]
Wow. That's strange. We could try to remove the shared resources before allocating on Windows.

**Comment by kaneplusplus** [comment]
Or we could check and kick back an error but then we'd have different functionality on different platforms.

**Comment by cdeterman** [comment]
Not sure, I tried to remove the backing and descriptor files but nothing there.  How could we check and remove the shared resources?  

I can't see any harm in implementing such a 'manual' removal of the shared resources when you are intending to overwrite them anyway.  I think that can be used on all platforms so functionality is consistent.

**Comment by cdeterman** [comment]
I believe I have narrowed down the problem to a weird permissions issue with the backingfile that is created.  If I forcefully delete the backingfile from CMD on Windows I can create consecutive `filebacked.big.matrix` objects.

For some strange reason though, the permissions (which look identical to the description file which will overwrite/delete) won't allow me to delete the backing file from within R or with C++.  I keep getting permission denied from things like `file.remove` and even using `remove` directly in the C++ fails to remove the file.  Somehow, when the file is created in the `CreateFileBackedMatrix` function in the `BigMatrix.cpp` file there is some property that is only assigned on windows preventing overwriting the file.

**Comment by phaverty** [comment]
Good detective work!  Is there some Boost function that releases the
mmapped memory? Perhaps we need to call that first?

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

On Tue, Jul 21, 2015 at 10:01 AM, Charles Determan <notifications@github.com

**Comment by cdeterman** [comment]
Although, not a solution, some more information I discovered.  If I `rm` the R object the refers to the `filebacked.big.matrix`, call `gc()`, then I can delete the file or simply overwrite it with the same `filebacked.big.matrix` call.  So the destructor is working appropriately when the `gc()` is called **after the R object is removed**.  What appears to be the problem is, albeit only on Windows, if you want to overwrite an existing object you need to first delete the object, `gc`, and then you can overwrite.  After some thought, this actually doesn't appear to be a horrible behavior where you may not want to overwrite an existing mapped file that is *in use* (perhaps a warning?).  

But when trying to replace the exact same thing it is a problem.  I don't know if there is a destructor that can be called when overwriting an R object because the original object should be removed (but it doesn't appear to immediately).  I proved this to myself by inserting a `gc()` to the beginning of the `filebacked.big.matrix` function.  If I remove the first matrix and replicate the call, it works, but I still need to remove the object before I can overwrite the mapped file.

Does anyone have any thoughts regarding what behavior you think should be implemented?

1. Always overwrite existing backing files (as Linux appears to do)?
2. Provide a warning to the user stating 'overwriting previous mapping file'?
3. Provide error (i.e. enrich current error) to stop user from overwriting map file unless R object deleted?
4. Other thoughts?

**Comment by phaverty** [comment]
I like #3.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by cdeterman** [comment]
@kaneplusplus did you have any thoughts?  If we decide option 3 is the best then Windows will be fine and we would change the behavior on Linux.  This mainly would include figuring out how to prevent the overwriting if the **R object** exists on Linux (which it doesn't appear to).  It is a mystery to me why the R object on Linux doesn't appear to be connected to the file whereas on Windows it is.

**Comment by kaneplusplus** [comment]
I like #3 as well. @cdeterman if you have time to do it that's great. Otherwise I can probably get to it this weekend.

The fix can be done from R. In the create functions a check is performed to see if the file exists. If so the error is triggered otherwise it proceeds as usual.

**Comment by cdeterman** [comment]
The fix is trivial if we just want to say if the file exists, don't overwrite it.  

However, if we prefer the option where if there is an existing R object using that file (which appears to be the default with Windows) it is more complicated and I'm not quite sure how to approach that from the Linux end.  On Linux, R doesn't seem to register that there is a connection between the R object and the file because I could create a second `filebacked.big.matrix` and overwrite the backing file of the first matrix without any problems.  Clearly not something we want but not sure how to force that relationship.

**Comment by kaneplusplus** [comment]
I prefer the trivial fix. If someone is creating a filebacked big matrix it is presumed to be big and a fair amount of processing went into creating it. In that case, I like the idea of guarding against accidentally overwriting it but providing an error message that tells the user how to explicitly get rid of it.

**Comment by cdeterman** [comment]
Okay, I can take care of this then as it shouldn't take very long.  I have also fixed the documentation warnings within my current edits so I can just provide a pull request once everything is updated and I believe all the builds should complete successfully.

**Comment by kaneplusplus** [comment]
OK, I have a little bit of time. I'll see if I can get the AppVeyor build working for Windows.

**Comment by cdeterman** [comment]
I just got the build to complete successfully on AppVeyor with the filebacking fix.  If the Travis CI passes I will create a pull request.

**Comment by phaverty** [comment]
Great!

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by cdeterman** [comment]
@phaverty Will this update, you may need to check your tests/examples in your bigmemoryExtras package.  If you create more than one `filebacked.big.matrix` object you will need to explicitly remove the R object, call `gc()` and `file.remove` on the backing files.  Just a heads up if you try to upgrade immediately.

**Comment by kaneplusplus** [comment]
Excellent! Thanks Charles.

BTW will either of you be at JSM?

**Comment by cdeterman** [comment]
@kaneplusplus I wasn't actually aware of that conference.  Given my schedule ATM it is unlikely I will be able to attend.  Perhaps next year.

**Comment by phaverty** [comment]
Sorry, not me.  Bummer.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by snowpong** [comment]
> Although, not a solution, some more information I discovered. If I `rm` the R object the refers to the `filebacked.big.matrix`, call `gc()`, then I can delete the file or simply overwrite it with the same `filebacked.big.matrix` call. 

Maybe this workaround can be provided somewhere in the documentation? Either as a note on file-backed big.matrix on Windows, or even in the error output currently implemented?

It took me quite a while to find this thread when I was truing to figure out why I couldn't delete my backingfile.
