### ISSUE TITLE
Binary backing file not consistent

### ISSUE THREAD

**Issue by kindlychung** [kaneplusplus/bigmemory#17]
Here is the code:

    # test big.matrix
    x = matrix(4, 2, 2)
    y = as.big.matrix(backingfile = "test.bin", descriptorfile="test.desc", backingpath = "/tmp", binarydescriptor=TRUE, x = x)
    y[, ]

On Ubuntu 15.04:

	kaiyin@tron 18:58:11 | /tmp =>
			xxd -b test.bin
	0000000: 00000000 00000000 00000000 00000000 00000000 00000000  ......
	0000006: 00010000 01000000 00000000 00000000 00000000 00000000  .@....
	000000c: 00000000 00000000 00010000 01000000 00000000 00000000  ...@..
	0000012: 00000000 00000000 00000000 00000000 00010000 01000000  .....@
	0000018: 00000000 00000000 00000000 00000000 00000000 00000000  ......
	000001e: 00010000 01000000

On Mac OS 10.10:

	kaiyin@kaiyins-mbp 18:59:48 | /tmp =>
			xxd -b test.bin
	0000000: 00000000 00000000 00000000 00000000 00000000 00000000  ......
	0000006: 00010000 01000000 00000000 00000000 00000000 00000000  .@....
	000000c: 00000000 00000000 00010000 01000000 00000000 00000000  ...@..
	0000012: 00000000 00000000 00000000 00000000 00010000 01000000  .....@
	0000018: 00000000 00000000 00000000 00000000 00000000 00000000  ......
	000001e: 00010000 01000000 00000000

As you can see, there is an extra null byte on mac.

**Comment by phaverty** [comment]
Hi Kaiyin,

Thanks for the report. Are there any inconsistencies at the R level? I
suspect that the difference is deep in glibc or the Mac equivalent.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by kindlychung** [comment]
You are welcome. 
At the R level everything looks the same. I found this out because I was trying to manipulate the underlying binary data in an R package that I have been developing.

**Comment by phaverty** [comment]
That sounds interesting. I suspect that if you manipulate the binary data
using the same "Boost" library that we use for our memory mapped data
structures, everything will work out. I don't know of anything we can do to
change this behavior. We don't have anything in there that intentionally
works differently on Mac or linux. Perhaps some of the better C++ people on
our team will know more.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by kaneplusplus** [comment]
Thanks for reporting this. To add to Pete's comment, it looks like Mac includes eof for the memory mapped file. Linux must keep track of the end of the file elsewhere. My hunch is that this is happening at the system level and that you'd see something similar by calling mmap directly from C.

In any case, it doesn't seem to be causing problems with functionality. It is certainly something that we should be aware of but maybe not something we need to fix/change.

**Comment by mcol** [comment]
Is this possibly due to this?
https://github.com/kaneplusplus/bigmemory/blob/master/src/BigMatrix.cpp#L846

**Comment by kaneplusplus** [comment]
Thanks for tracking this down. I do remember problems with binary incompatibilities between Linux and Windows. In particular, Windows and Mac didn't support `ftruncate`. So, we used stream buffers. However, I don't remember the reason for the code you reference.

Please note that we don't claim binary file compatibility across platforms. If you'd like to try the code without `sputc` we'd be interested in seeing the result.
