### ISSUE TITLE
What are the current limitations for windows?

### ISSUE THREAD

**Issue by cdeterman** [kaneplusplus/bigmemory#2]
I am well aware that bigmemory is not currently installable for Windows.  I was wondering what are the current reasons that it is limited?  What about Windows is preventing the package from being platform independent?

**Comment by kaneplusplus** [comment]
The BH package, which bigmemory relies upon generates a warning in valgrind during a CHECK on CRAN. The warning comes from a line in the boost library and is not a problem (a valgrind warning does not imply a problem it simply shows where there may be problems). I have explained this to them and they have been unwilling accept the package.

On Windows I recommend installing [Rtools](http://cran.r-project.org/bin/windows/Rtools/). You can used devtools to install bigmemory with ```devtools::install_github("kaneplusplus/bigmemory")```.

**Comment by kaneplusplus** [comment]
Also, I just took a look at your repos. If there's anything you'd like to contribute please feel free to send a pull request. Also, if you're interested we're happy to give authorship to consistent contributors (like Peter Haverty). Thanks!

**Comment by cdeterman** [comment]
Thank you, I work with big data quite a bit and helping increase functionality in R is something I want to be a part of.  If you look at my repos, the major changes I have made is to make them Rcpp and Roxygen2 compatible to make it simpler to update and add functions.  I was holding off on making and pull requests until I had something more significant to contribute.  

I will look in to the installation on Windows as well.  I think I recall doing something like that previously but it would only install either 32 or 64 bit versions but not both.  I will get back to you if there are issues.

**Comment by kaneplusplus** [comment]
Rcpp and Roxygen2 are the two biggest features on my wish list for bigmemory. It would be great to see them incorporated. 

There's no hurry with the request since I won't have a lot of time on my hands for the next few weeks. But please don't hesitate to contact me if you run into any questions or need me to help with the effort.
