### ISSUE TITLE
Define Location of 'backing counter' files?

### ISSUE THREAD

**Issue by cdeterman** [kaneplusplus/bigmemory#22]
When I create a given `big.matrix` object a series of associated files (counter, counter_mutex, etc.) are created in to a system defined temporary directory.  For example, I have seen `/dev/shm` and `/run/shm`.  Is there a way to define an alternate directory where these files could go?  If not, perhaps a similar option that is available in `bigalgebra` with `options(bigalgebra.tempdir)` would be preferable.  This way a user can place these files in a defined location and can deal with them separately from other temp files if they so wish.

**Comment by kaneplusplus** [comment]
If I remember correctly ```/dev/shm``` is where all mmap'ed, named shared-memory resources are kept. We can definitely change the location of the counter. I'm not sure about the counter_mutex but I it'll probably work. The process for creating those shared resources may also have to change a little bit but I don't think it would be too bad.

However, would you really want to do this? I think the counter and mutex are only used for shared-memory big.matrices. If you move them from ```/dev/shm``` they will no longer exist only in shared memory. They will be in files on a hard drive.

**Comment by cdeterman** [comment]
Ah, that is right.  I completely overlooked the fact that `/dev/shm` is for shared-memory.  Perhaps another angle to this question then, can we get the shared memory object name in the `/dev/shm` directory?  The reason behind these questions is in the context of servers where they are almost never restarted the files created can build up.  If the user can get the name then they could explicitly cleanup when they complete their analysis without the need to restart.  Thoughts?

**Comment by cdeterman** [comment]
I realized that we already have the `shared.name` function.  I will close this issue.  My own oversights.

**Comment by kaneplusplus** [comment]
No problem. I'm happy to answer questions. The line count for the project is big enough that it's sometimes more efficient for me just to answer the question.
