### ISSUE TITLE
Missing GetIndivMatrixElements in RcppExports

### ISSUE THREAD

**Issue by kaneplusplus** [kaneplusplus/bigmemory#25]
When building I'm getting the following note:
```
GetIndivElements.bm: no visible global function definition for
  ‘GetIndivMatrixElements’
```

It looks like this is happening because ```GetIndivElements.bm``` in bigmemory.R is calling ```GetIndivMatrixElements```, which isn't defined.

I think the there should be a ```GetIndivMatrixElements``` in RcppExports.R should call ```GetIndivMatrixElements``` in bigmemory.cpp. However, I'm a little bit confused by the signature.

**Comment by cdeterman** [comment]
Ah, that is because of syntax error I made with the Rcpp attributes.  I will push a fix shortly.  Thanks for noticing that error.
