### ISSUE TITLE
Current state on Windows unclear

### ISSUE THREAD

**Issue by agrueneberg** [kaneplusplus/bigmemory#30]
Hi Michael,

I see that a lot of work has been done since this questions has been asked last time (see #2), and I had no problems installing the package from CRAN on a virtual machine running Windows, so I am wondering if there are any remaining issues with Windows support? http://bigmemory.org still mentions that "updating bigmemory with restored support for Windows" is a work in progress.

Thanks,
Alex

**Comment by kaneplusplus** [comment]
Thanks. It is supported. I need to update this.

**Comment by agrueneberg** [comment]
Good to know, thanks! Hope you will find some time to update the page soon.

**Comment by kaneplusplus** [comment]
I will. Thanks for the reminder.

**Comment by agrueneberg** [comment]
Thanks for updating the page, Michael.
