### ISSUE TITLE
big.matrix doesn’t store row names

### ISSUE THREAD

**Issue by kaneplusplus** [kaneplusplus/bigmemory#34]
Someone else described the same problem in stackoverflow:

http://stackoverflow.com/questions/12576735/bigmemory-and-rownames-dimnames-of-matrix

**Comment by kaneplusplus** [comment]
I'm having trouble reproducing this one.
```{R}
require(bigmemory)
options(bigmemory.allow.dimnames=TRUE)
im = as.matrix(iris[,-5])
rownames(im) = paste0("row_", 1:nrow(im))
bim = as.big.matrix(im)
bim2 = attach.big.matrix(describe(bim))
rownames(bim2)
```

**Comment by remstef** [comment]
The issue is in `read.big.matrix`. Try:
```
require(bigmemory)
options(bigmemory.allow.dimnames=TRUE)

rownames(iris) = paste0("row_", 1:nrow(iris))
write.table(iris[,-ncol(iris)], file = 'iris.txt', col.names=T, row.names = T, sep = ' ', quote=F)

bim <- read.big.matrix('iris.txt', sep=' ', header=T, has.row.names = T, backingfile = 'iris.bin', descriptorfile = 'iris.desc')
rownames(bim)

bim2 = attach.big.matrix("iris.desc")
rownames(bim2)
```

**Comment by privefl** [comment]
Try using `devtools::install_github("privefl/bigmemory", ref = "develop")`. 
This should be fixed now. The problem was that the rownames were written to the `big.matrix` object but not to the descriptor file.

**Comment by remstef** [comment]
That works, thanks!

**Comment by privefl** [comment]
I think I introduced a bug in my code, which is not covered by tests. 
Trying to fix it..
