### ISSUE TITLE
How to use big.matrix with raw bytes?

### ISSUE THREAD

**Issue by adamryczkowski** [kaneplusplus/bigmemory#42]
It seems, that big.matrix of type char is... char, i.e. *signed* byte. For R it is *unsigned* (there is no *singed byte* in R). 

How to store a byte in a big.matrix? 

Or: how to make this test pass?
```
test_that("Reading and writing byte>=128 on memory-backed file",{
        m<-big.matrix(10,1,type='char')
	m[4,1]<-as.raw(130)
	expect_equal(m[4,1],130)
})
```

**Comment by adamryczkowski** [comment]
I've added a patch for that together with the unit test. Please add it upstream, so I can build my package on top of that more easily.

**Comment by kaneplusplus** [comment]
Thanks very much Adam. It has been reviewed and merged.
