### ISSUE TITLE
object of type 'S4' is not subsettable

### ISSUE THREAD

**Issue by privefl** [kaneplusplus/bigmemory#44]
```
a <- big.matrix(3, 3)
m <- matrix(1:6, 2, 3)
a[1:2, ] <- m
```
now gives
```
Error in a[1:2, ] <- m : object of type 'S4' is not subsettable
```

This seems to be a problem only when accessing a subset of rows.
It worked in earlier versions (don't know which though).

I now use `a[1:2, ] <- as.numeric(m)` which less straight-forward but works.

**Comment by cdeterman** [comment]
Ah, this is because there isn't an S4 method for `matrix` classes.  This will need to be added explicitly.

**Comment by privefl** [comment]
Thanks, seems to work again.

**Comment by privefl** [comment]
I installed your version. It seems to work.
Please close this issue when you merge.

**Comment by cdeterman** [comment]
Naturally.   I am waiting on @kaneplusplus to complete the merge.

**Comment by kaneplusplus** [comment]
Merged. Thanks very much.
