### ISSUE TITLE
Test coverage is low

### ISSUE THREAD

**Issue by adamryczkowski** [kaneplusplus/bigmemory#46]
@kaneplusplus  The bigmemory package has low test coverage, so it is easy to add a feature, that breaks something else. (I will add the quoted `m[1:2,1] == c(NA, -5)` to the tests)

When I was browsing the code, I found a lot of repetitions, which are places that can easily introduce errors when the package evolve. I am willing to put some time and effort to write the unit tests and to refactor the code to eliminate the redundacies and possible bugs. But since it is your project, I would like to first discuss with you your vision of this package, so I don't waste my time doing things that would ultimately get rejected.

Can we talk via VoIP (e.g. Skype) sometime?

**Comment by cdeterman** [comment]
@adamryczkowski the test coverage is actually not correct.  There is something strange happening with coveralls on the travis ci that isn't working properly.  Locally, I can run `covr::package_coverage` and it is over 60%.  More unit tests are always appreciated to cover more of the package but I don't want you to get the impression that barely anything is currently covered.

**Comment by adamryczkowski** [comment]
I didn't mean that. But true, my judgement was influenced by the GitHub's value.

**Comment by kaneplusplus** [comment]
@adamryczkowski if you'd still like to talk that's fine with me. @cdeterman if you'd like to join that would be great.

**Comment by privefl** [comment]
I could contribute too because the package that I will develop during my thesis depends on bigmemory.
Although, I'm more skilled in R(cpp) than pure C.

**Comment by cdeterman** [comment]
@privefl that's fine.  It is currently a push (mostly from me) to use much less C in bigmemory.  Converting the rest of its' internals to using Rcpp (I did the original conversion) has been a goal of mine but I've lacked the time to do so.  Always happy to get more people concerned with testing and package coverage and consistency.

**Comment by adamryczkowski** [comment]
Nice. I live where clocks are set in GMT +1. At the moment I am freelancer, and so I am flexible about time.

Is Skype (R) good enough for you, or would you rather talk using something else (I would gladly learn about a better VoIP than Skype ;-) ).

**Comment by privefl** [comment]
I'm in holidays until October 2, so same for me. GMT+1 too (France). I'm better at writing than speaking English but it should be OK x)

**Comment by privefl** [comment]
The problem of coverage is a problem with coveralls or with travis (.yml file)?

I use codecov for my packages and it works fine, maybe try it?

**Comment by cdeterman** [comment]
@privefl I have actually tried codecov as well ([see here](https://codecov.io/gh/cdeterman/bigmemory/tree/42faa982a55f8cf082e7c654879441657332323a)).  I have been trying to troubleshoot it in another issue [here](https://github.com/jimhester/covr/issues/184).

**Comment by privefl** [comment]
I'll try to look at it later.

**Comment by cdeterman** [comment]
I believe we can close this issue now?  Unless we want to leave it open for our potential chat session?
