### ISSUE TITLE
Add the size of the allocation in the Create* functions in BigMatrix.cpp

### ISSUE THREAD

**Issue by kaneplusplus** [kaneplusplus/bigmemory#5]

**Comment by kaneplusplus** [comment]
A new member of BigMatrix has been added, called ```_allocationSize``` which keeps track of the total number of bytes allocated to a BigMatrix object. This value of this member can be found using the ```allocation_size``` method.

**Comment by cdeterman** [comment]
Thank you for adding this method however something appears to be broken.  I installed from you git repo with `devtools::install_github("kaneplusplus/bigmemory")` and now creating a basic big.matrix object with `big.matrix(3,3, init=1)` results in the following error:

    Error in big.matrix(3,3, init=1) : 
      Error: memory could not be allocated for instance of type big.matrix

After some quick hunting it appears the call is not getting passed the following section within `createRAMMatrix`

    if (!pMat->create( static_cast<index_type>(NUMERIC_VALUE(row)),
      static_cast<index_type>(NUMERIC_VALUE(col)),
      INTEGER_VALUE(typeLength),
      static_cast<bool>(LOGICAL_VALUE(separated))))
    {
      delete pMat;
      return NULL_USER_OBJECT;
    }

Was this working for you?

**Comment by kaneplusplus** [comment]
Shoot, I'll check it now. I may have forgotten to delete an object file.

**Comment by cdeterman** [comment]
Thanks, the fix works on a Linux (Ubuntu) system but for some reason still fails on Windows.  I normally work on Linux so it doesn't bother me much but not sure why it is crashing there.

**Comment by kaneplusplus** [comment]
I'm not sure why it's not working on windows. I'll try to take a look this week.
