### ISSUE TITLE
Questions on dev

### ISSUE THREAD

**Issue by privefl** [kaneplusplus/bigmemory#57]
I'm starting to put my nose in the code of this package to 
- understand it better,
- try to solve some problems,
- try to add some features.

I have some questions on some choices of implementation. It will be mostly C/C++ questions as I'm more comfortable with R. They may sound "stupid" to you.

I will use this conversation to ask my questions and hope for your answers, so that I can contribute more to this package.

**Comment by privefl** [comment]
First question:
- what it `index_type`?
- where it is defined (some file / std)?
- why not just using `int`? Can it be replaced by an `int`?

**Comment by privefl** [comment]
Second question:
Is there still a use of adding extra information (NumericVector of size 2) of ncol and nrow in colOffset and rowOffset of descriptors?

**Comment by kaneplusplus** [comment]
The ```index_type``` is the type that is used to index into a C-array. It is defined in ```bigmemoryDefines.h``` as ```intptr_t``` which is guaranteed to be 64-bits on a 64-bit machine. The ```int``` type is insufficient because it is only 32-bits and would only let you index 2^31-1 values in a C-array.

I think ```colOffset``` and ```rowOffset``` are used in ```sub.big.matrix``` objects, which are essentially windows into larger ```big.matrix``` objects.

**Comment by privefl** [comment]
Are there people who have datasets with more than 2 billion rows or columns? 

This is OK for `colOffset` and `rowOffset`. What I meant is that when you get a descriptor of a `big.matrix`, you have the slots `$colOffset` and `$rowOffset` in the `@description` which are vectors of size 2 (the offset and the dimension), while the dimension is also given in `$ncol` and `$nrow`.
And, I can't see where this extra information (second element of the vectors) is used in the code.

**Comment by kaneplusplus** [comment]
There are people who routinely use ```big.matrix``` objects with more than 2 billion elements.
