### ISSUE TITLE
attaching a file backed big matrix fails when using '~' in backingpath on OS X

### ISSUE THREAD

**Issue by absvm** [kaneplusplus/bigmemory#61]
Currently I am on R 3.3.2, with bigmemory 4.5.19, OS X 10.11.6.

I noticed that when I use the tilde ('~') in a backing path of a file backed big matrix, attaching the matrix fails. It's a minor issue, I can work around it, but I think it's worth sharing with the community since it took me quite some time to find out what went wrong.

Here is the code that reproduces the error:

```
library(bigmemory)

options(bigmemory.typecast.warning=FALSE)

# create a simple filebacked matrix
BM = filebacked.big.matrix(10, 10, type = "integer", init = 5,
                            backingfile = 'M.bin',
                            backingpath = '~/Documents', descriptorfile='M.desc')

BMdescription <- describe(BM)

# attach it from the backing file
y <- attach.big.matrix(BMdescription, backingpath='~/Documents')

```
 
and the error:

```
Error in attach.resource(obj, path = list(...)[["backingpath"]], ...) : 
  Fatal error in attach: big.matrix could not be attached.
```

**Comment by privefl** [comment]
Thanks for the feedback.

I think your example now works in the latest version of the package.
You can install it using `devtools::install_github("cdeterman/bigmemory")`.

Also note that you can now attach without specifying the `backingpath`. 
Try just `y <- attach.big.matrix(BMdescription)`.

If it's okay, please close this issue (I can't). 
Hope I helped.

**Comment by absvm** [comment]
Great, it works. Also very good to have the backingpath now being stored in the descriptor, so I can attach the matrix without specifying it separately.

Thanks!
