### ISSUE TITLE
object of type 'S4' is not subsettable when using dim names for subsetting

### ISSUE THREAD

**Issue by mlist** [kaneplusplus/bigmemory#79]
Hi, 

the newest version of the bigmemory package on CRAN (4.5.28) introduced an issue. big.matrix used to support subsetting by dim names, e.g. row and column names. Now this leads to the error: `object of type S4 not subsettable` 

Example:

```
test_big_matrix <- big.matrix(nrow = 5, ncol = 5, 
                              dimnames = list(
                                  c("A", "B", "C", "D", "E"), 
                                  c("F", "G", "H", "I", "J")))
test_big_matrix[,] <- 0 #works
test_big_matrix[c("A", "D"), c("H", "J")] <- 1 #used to work
```

I also tried if setting this option helps but it did not:

```
$bigmemory.allow.dimnames
[1] TRUE
```

**Comment by privefl** [comment]
Maybe the same problem as in https://github.com/kaneplusplus/bigmemory/issues/77

**Comment by mlist** [comment]
Yeah I believe this one has the same cause but the bugfix that was implemented works only for logical subsetting, right?

**Comment by kaneplusplus** [comment]
I think @mlist is correct, this is a bug. I've added the example to our unit test. I'll try to get to it in the next few days.

@privel I think it is related to #77. At some point, we lost some assignment capabilities.

**Comment by kaneplusplus** [comment]
@mlist @privefl OK, I think it's fixed. If I don't hear about any more problems, I'll upload to CRAN this weekend.
