### ISSUE TITLE
bigmemory is not installing on the Mac.

### ISSUE THREAD

**Issue by kaneplusplus** [kaneplusplus/bigmemory#9]

**Comment by cdeterman** [comment]
Although not a solution (I don't have access to a Mac) we may want to look in to using a continuous integration service like Travis CI (you can see examples with Hadley's packages like testthat or ggplot2).  That way if any new additions or changes happen we will know if it breaks.  Food for thought.

**Comment by phaverty** [comment]
CI is a wonderful thing. I don't imagine that CRAN or GitHub provide a free
service, do they?  We use Jenkins here. I can probably add the bigmemory
stuff to our setup to make sure we are OK on Linux at least.  I have a Mac
and can periodically update, check and install.  I'm sure there is a better
way to get Windows and Mac checks, though.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

On Wed, Apr 29, 2015 at 12:55 PM, Charles Determan <notifications@github.com

**Comment by cdeterman** [comment]
If your project is open source you can use Travis CI (Linux definitely, Mac I think so too) with you github repo for free.  You can also use [appveyor](http://www.appveyor.com/) for testing Windows (also free for open source).  Both of these services are used with multiple R packages such as those I mentioned above by Hadley.

**Comment by kaneplusplus** [comment]
OK, I've got the fix for the compile error. I'm going to fix the warnings now. However, the point is well taken. I'll see what needs to be done for automated builds after it's done.

**Comment by kaneplusplus** [comment]
OK, we now have Travis-CI integration. I've added appveyor and coveralls. I'll check on them later but I've added issues for them.
