### ISSUE TITLE
Manually finalize a bigmemory object

### ISSUE THREAD

**Issue by nbenn** [kaneplusplus/bigmemory#93]
I'm in the situation where I would like to manually trigger the destructor of a shared `big.matrix` object instead of waiting for all references to go out of scope/be `rm`ed and the gc doing it's thing. I don't think this is currently possible. Or am I mistaken? Do others consider such functionality useful as well?

**Comment by privefl** [comment]
I'm not sure to see the use case.
Could you explain more in detail yours please?
