### ISSUE TITLE
(seeking advice, not a complaint) read.big.matrix appears to hang on AMD Win 7 with big matrix

### ISSUE THREAD

**Issue by ecoquant** [kaneplusplus/bigmemory#96]
I have a challenging problem, involving a read of an integer matrix having 273,390,744 rows and 7 columns.  I add 30 additional "dummy" columns in the read. All values are integer. 

The dataset is 5.9 GB and is a flat file, tab-delimited. 

A call to `read.big.matrix` is made as

```
M16<- read.big.matrix(filename="D16.data", sep="\t", header=TRUE, row.names=NULL, 
                      has.row.names=FALSE, type="integer", skip=0, separated=FALSE, 
                      backingfile="M16.bin", backingpath="./bigmemory/", 
                      descriptorfile="M16.descr", binarydescriptor=TRUE,
                      extraCols=c(sapply(1:20, FUN=function(n) sprintf("ev%-.0f", n)),
                                  sapply(0:23, FUN=function(n) sprintf("h%02.0f", n))),
                      shared=TRUE)
```

Apparently something is built, but the Windows 7 system freezes, including the elapse time-of-day clock. 

![bmf_2019-10-10_145518](https://user-images.githubusercontent.com/4048647/66598067-38992000-eb6e-11e9-8c59-63c1966f1316.jpg)

```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
```

![sys_2019-10-10_150110](https://user-images.githubusercontent.com/4048647/66598359-e278ac80-eb6e-11e9-8a84-01dd516213c7.jpg)

I am about to proceed to subdivide the data files to see if there is a threshold below which it does work. I'm writing simply to see if any other users have had similar experiences.  Is this just too big?

Thanks,

 - Jan

**Comment by privefl** [comment]
From what I remember from the code, `read.big.matrix()` writes rows by rows, which can be slow if you have large data.

I would recommend to use `bigstatsr::big_read()` (disclaimer: my package) to read the file, which reads it column by column (see tuto [here](https://privefl.github.io/bigstatsr/articles/read-FBM-from-file.html)).
Then, you could add some extra columns using `$add_columns()`.

You can always go back to using {bigmemory} with `$bm()` afterwards as `FBM` objects and `big.matrix` objects are very similar (see [vignette](https://privefl.github.io/bigstatsr/articles/bigstatsr-and-bigmemory.html) for more info).

**Comment by ecoquant** [comment]
Awesome, @privefl ... I will give it a try!

Thanks much.

**Comment by ecoquant** [comment]
@privefl .... Worked like a charm. Highly recommended.  Now to see what I can _do_ with these. 

Closing ticket.
